/*
 * EXT_INT_Config.h
 *
 *  Created on: Aug 16, 2023
 *      Author: yosse
 */

#ifndef MCAL_EXTERNAL_INTERRUPT_EXT_INT_CONFIG_H_
#define MCAL_EXTERNAL_INTERRUPT_EXT_INT_CONFIG_H_





/**
 * OPTIONS:
 * 			EXT_INT_INT_PULLUP_DISABLE
 * 			EXT_INT_INT_PULLUP_ENABLE
 *
 */
#define EXT_INT0_INTERNAL_PULLUP	EXT_INT_INT_PULLUP_DISABLE
#define EXT_INT1_INTERNAL_PULLUP	EXT_INT_INT_PULLUP_DISABLE
#define EXT_INT2_INTERNAL_PULLUP	EXT_INT_INT_PULLUP_DISABLE


#endif /* MCAL_EXTERNAL_INTERRUPT_EXT_INT_CONFIG_H_ */
