/*
 * UART_config.h
 *
 *  Created on: Aug 23, 2023
 *      Author: yosse
 */

#ifndef MCAL_UART_UART_CONFIG_H_
#define MCAL_UART_UART_CONFIG_H_

#define  UART_D_TXSPEED_DISABLE			0
#define  UART_D_TXSPEED_ENABLE			1

#define UART_D_TXSPEED_CFG			UART_D_TXSPEED_DISABLE

#define UART_DATALEN_8BIT	 		0x03
#define UART_DATALEN_9BIT	 		0x07

#define UART_DATA_LEN_CFG			UART_DATALEN_8BIT

#define UART_STOPBIT_1BIT	0
#define UART_STOPBIT_2BIT	1

#define UART_STOPBIT_LEN_CFG		UART_STOPBIT_2BIT

#define UART_PARITY_DISABLE			0x00
#define UART_PARITY_EVEN			0x02
#define UART_PARITY_ODD				0x03

#define UART_PARITYMODE_CFG			UART_PARITY_DISABLE


// xtal 8mhz , no double speed

#define UART_BAUDRATE_9600			51

#define UART_BAUDRATE_CFG		UART_BAUDRATE_9600

#define UART_INTERRUPT_FEATURE_DISABLE		0
#define UART_INTERRUPT_FEATUER_ENABLE		1

#define UART_RX_INTERRUPT_CFG	UART_INTERRUPT_FEATURE_DISABLE

#endif /* MCAL_UART_UART_CONFIG_H_ */
